# This pipeline is used as template to build the sfpowerscripts plugin


name: 'sfpowerscripts Plugin Build'

on:
  workflow_call:
    inputs:
      version:
        type: string
        default: ''
      publish:
        type: boolean
        default: false


jobs:
  build:
    name: 'Build Packages'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 'Set Git Config'
        run: |
          git config --global user.email "sfpowerkit.ci@dev.azure.com"
          git config --global user.name "sfpowerkitci"


      - name: 'Create .npmrc file in HOME directory'
        run: |
           echo "${{ env.NPM_SCOPE }}:registry=https://registry.npmjs.org" > ~/.npmrc
           echo  "_authToken=${AUTH_TOKEN}" >> ~/.npmrc
        env:
          AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 'Bootstrap Lerna'
        if: ${{ inputs.publish == 'true' }} || ${{ inputs.version == 'review' }}
        run: npx lerna bootstrap


      - name: 'Build  All  Packages'
        if: ${{ inputs.publish == 'true' }} || ${{ inputs.version == 'review' }}
        run: npx lerna run build


      - name: 'Run Core Unit Tests'
        if: ${{ inputs.publish == 'true' }}
        run: npm run test
        working-directory: ./packages/core


      - name: 'Run CLI Unit Tests'
        if: ${{ inputs.publish == 'true' }}
        run: 'npm run test'
        working-directory: ./packages/sfpowerscripts-cli


      - name: 'Upload Coverage Results'
        if: ${{ inputs.publish == 'true' }}
        run: 'curl -s https://codecov.io/bash'
        shell: bash
        working-directory: ./packages/core


      - name: 'Publish CLI/Core'
        if: ${{ inputs.publish == 'true' }}
        run: 'npx lerna publish from-package --yes --dist-tag ${{ inputs.version }}'
        working-directory: ./