# This pipeline builds the sfpowerscripts plugin

name: 'sfpowerscripts Build Pipeline'

on:
  push:
    branches:
      - develop
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'decision records/**'
      - 'demoreel/**'
      - 'prerequisites/**'

  workflow_dispatch:


jobs:
#Merge to Develop, Deploy Alpha builds
  alpha:
    name: 'Alpha Builds'
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/develop' }}
    environment:
      name: alpha
    concurrency: alpha
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Packages
        uses: Accenture/sfpowerscripts/.github/workflows/buildPackages.yml@develop
        timeout-minutes: 20
        with:
          version: 'alpha'
          publish: true

# Hotfix stage
  hotfix:
    name: 'Hotfix'
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    environment:
      name: hotfix
    concurrency: hotfix
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Packages
        uses: Accenture/sfpowerscripts/.github/workflows/buildPackages.yml@develop
        timeout-minutes: 20
        with:
          version: 'hotfix'
          publish: true

  sfpowerscripts-beta:
    uses: ./.github/workflows/promotePackage.yml
    with:
      version: 'beta'
      pathToPackageJson: 'packages/sfpowerscripts-cli/package.json'
    if: ${{ github.ref == 'refs/heads/develop' }}
    needs: alpha

  sfpowerscripts-prod:
    uses: ./.github/workflows/promotePackage.yml
    with:
      version: 'latest'
      pathToPackageJson: 'packages/sfpowerscripts-cli/package.json'
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
    needs: [beta, hotfix]

  core-beta:
    uses: ./.github/workflows/promotePackage.yml
    with:
      version: 'beta'
      pathToPackageJson: 'packages/core/package.json'
    if: ${{ github.ref == 'refs/heads/develop' }}
    needs: alpha

  core-prod:
    uses: ./.github/workflows/promotePackage.yml
    with:
      version: 'latest'
      pathToPackageJson: 'packages/core/package.json'
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
    needs: [beta, hotfix]

  sfp-beta:
    uses: ./.github/workflows/promotePackage.yml
    with:
      version: 'beta'
      pathToPackageJson: 'packages/sfp-cli/package.json'
    if: ${{ github.ref == 'refs/heads/develop' }}
    needs: alpha

  sfp-prod:
    uses: ./.github/workflows/promotePackage.yml
    with:
      version: 'latest'
      pathToPackageJson: 'packages/sfp-cli/package.json'
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
    needs: [beta, hotfix]
