# This pipeline builds the sfpowerscripts plugin

name: 'sfpowerscripts Build Pipeline'

on:
  push:
    branches:
      - develop
      - release/**
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'decision records/**'
      - 'demoreel/**'
      - 'prerequisites/**'

  workflow_dispatch:


jobs:
#Merge to Develop, Deploy Alpha builds
  alpha:
    name: 'Alpha Builds'
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/develop' }}
    environment:
      name: alpha
    concurrency: alpha
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Packages (sfdx-plugin)
        uses: Accenture/sfpowerscripts/.github/workflows/buildcli.yml@develop
        timeout-minutes: 20
        with:
          commitToGit: true
          version: 'alpha'
          publish: true

# Beta Stage
  beta:
    name: 'Beta Builds'
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/develop' }}
    needs: alpha
    environment:
      name: beta
    concurrency: beta
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Packages (sfdx-plugin)
        uses: Accenture/sfpowerscripts/.github/workflows/buildcli.yml@develop
        timeout-minutes: 20
        with:
          commitToGit: false
          version: 'beta'
          publish: false

# Hotfix stage
  hotfix:
    name: 'Hotfix'
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/release/*' }}
    environment:
      name: hotfix
    concurrency: hotfix
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Packages (sfdx-plugin)
        uses: Accenture/sfpowerscripts/.github/workflows/buildcli.yml@develop
        timeout-minutes: 20
        with:
          commitToGit: false
          version: 'hotfix'
          publish: false

# Prod Stage
  prod:
    name: 'Prod Builds'
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/release/*' }}
    needs: [beta, hotfix]
    environment:
      name: prod
    concurrency: prod
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Packages (sfdx-plugin)
        uses: Accenture/sfpowerscripts/.github/workflows/buildcli.yml@develop
        timeout-minutes: 30
        with:
          commitToGit: false
          version: 'prod'
          publish: false
