# This pipeline is used as template to promote package


name: 'Promote Package'

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      pathToPackageJson:
        type: string
        required: true




# TODO: to be migrated to github actions syntax
jobs:
  promotePackage:
    name: 'Promote Package'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 'Set Git Config'
        run: |
          git config --global user.email "sfpowerkit.ci@dev.azure.com"
          git config --global user.name "sfpowerkitci"

      - name: 'Create .npmrc file in HOME directory'
        run: |
           echo "${{ env.NPM_SCOPE }}:registry=https://registry.npmjs.org" > ~/.npmrc
           echo  "_authToken=${AUTH_TOKEN}" >> ~/.npmrc
        env:
          AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 'Promote package $(jq -r ".name" ${{ inputs.packageToPackageJson }})'
        script: |
          PKG_NAME=$(jq -r ".name" ${{ inputs.packageToPackageJson }})
          PKG_VERSION=$(jq -r ".version" ${{ inputs.pathToPackageJson }})
          npm dist-tag add $PKG_NAME@$PKG_VERSION ${{ inputs.version }}
