# This pipeline is used as template to promote package


name: 'sfpowerscripts Promote Package'

on:
  workflow_call:
    inputs:
      version:
        type: string
        default: ''
      packageToPromote:
        type: object
        default:
          package: ''
          pjson: ''


# TODO: to be migrated to github actions syntax
jobs:
  promotePackage:
    name: 'Promote Package'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '14' 

      - name: 'Set Git Config'
        run: |
          git config --global user.email "sfpowerkit.ci@dev.azure.com"
          git config --global user.name "sfpowerkitci"

# TODO: find equivalent for gh actions / for confirmation with Alan
      - task: DownloadSecureFile@1
        displayName: 'Download secure file .npmrc'
        name: npmrc
        inputs:
            secureFile: '8abaf6dc-ff2e-427a-971b-a98cbd48af34' # Need to change this

      - task: npmAuthenticate@0
        inputs:
          workingFile: $(npmrc.secureFilePath)
          customEndpoint: npm

      - name: 'Move authenticated npmrc file to home directory'
        run: |
          mv $(npmrc.secureFilePath)  ~/.npmrc

      - name: 'Promote package ${{ inputs.packageToPromote.package }}'
        script: |
          PKG_VERSION=$(jq -r ".version" ${{ inputs.packageToPromote.pjson }})
          npm dist-tag add ${{ inputs.packageToPromote.package }}@$PKG_VERSION ${{ inputs.version }}
